server:
  port: 8888

github:
  Client_id: 7d6b24b8a3de9e888bf8
  Redirect_uri: http://localhost:8888/callback
  Client_secret: 118339bec369f82d4da15551749449457417520f

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootcommunity?useUnicode=true&characterEncoding=utf-8
    username: root
    password: hzs121914
    driver-class-name: com.mysql.jdbc.Driver